version: '3.8'
services:
  app:
    build: .
    container_name: bicitaxi_backend
    ports:
      - "3000:3000"
    env_file:
      - .env  
    depends_on:
      - db    
    networks:
      - bicitaxi_network 
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./app.js:/usr/src/app/app.js

  db:
    image: mysql:8.0
    container_name: bicitaxi_db
    ports:
      - "3307:3307"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - bicitaxi_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./databases/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  bicitaxi_network:
    driver: bridge
volumes:
  mysql_data: